### PR TITLE
Remove lastEvent tracking

### LINKED ISSUE #160: Remove lastEvent tracking
This feature is now pretty much redundant with breadcrumbs and is no longer necessary.

### PR DESCRIPTION
**Pull request by wordofchristian**
closes #160

### CODE REVIEW

**Comment by jacobmarshall** [comment]
Sorry, I missed this. What was the reason behind removing last event tracking?

**Comment by wordofchristian** [comment]
We decided it seems redundant now that we have breadcrumbs. Is there some reason we should keep it around?

**Comment by jacobmarshall** [comment]
Just noticed the original issue. Though breadcrumbs do cover off a lot of the ground which `lastEvent` did, there are still times where `lastEvent` helped provide a lot of clarity (where user integration is not involved). For instance `onmessage` on iframes, or `onload`/`onreadystatechange` for XHR.

Maybe it's worth including network requests (XHR/fetch) as another breadcrumb type? Just thinking aloud really. And maybe most people's use cases don't need to class XHR as a valuable event, however (especially on a timeline, like breadcrumbs) it would provide even more clarity. The only issue here is the bulk that adding more and more breadcrumb puts on the script file.

**Comment by jacobmarshall** [comment]
It's also not just XHR & iframes. There are many more events which are only really useful if they're the "last event" that happened, which don't get captured by breadcrumbs.

For instance, seeing that the last event is `keydown` on a `<textarea>`, instead of an `onclick` on a `<li>` for a typeahead component, narrows down the entry point of an error.

What do you think about a special type of breadcrumb which only shows the last occurrence for these kinds of events, so the feed doesn't get spammed? So the breadcrumb can still be used, but the functionality of `lastEvent` isn't lost entirely. Again, just thinking aloud. Not sure how other people use `lastEvent`, and whether or not we're alone here 😛

**Comment by jacobmarshall** [comment]
Sorry for triple commenting, but maybe this is worth me opening a new issue for this?

**Comment by eanakashima** [comment]
@jacobmarshall thanks, some great points here. I think our long-term goal is that breadcrumb tracking will be able to handle all of the lastEvent use cases and more — but there are a few we're missing right now. I've opened another issue (#166) to discuss which ones we'd like to add — if you think of any more, please let us know. ✨

**Comment by jacobmarshall** [comment]
Thanks @eanakashima, I appreciate it.

**Pull request merged**
