### PR TITLE
Offline support

### PR DESCRIPTION
**Pull request by jmshal**
#117

### CODE REVIEW

**Comment by eanakashima** [comment]
Hey @jacobmarshall, thanks for opening this, really excited about it. There's been a bit of a delay on us merging in this and one or two other large PRs, because it will put us over the [4604 gzip'd bytes of js](https://github.com/bugsnag/bugsnag-js/pull/57#issuecomment-47064821) size discussed in prior issues, so we're thinking a little more about how we want to structure additional features on top of bugsnag-js. We'll report back when we have an update. Sorry for the wait!

**Comment by jacobmarshall** [comment]
Sounds good, thanks for letting me know.

My two cents on the matter - maybe making these kinds of larger additions available as addons (`bugsnag-js/workers` and `bugsnag-js/offline`) for people to optionally include wouldn't be such a bad idea? People bundling their app's dependencies in a seperate vendor file (for instance) probably have a much larger overall file size anyway.

**Comment by ticky** [comment]
@eanakashima is this likely to land anytime soon?

We’ve got some issues we’re trying to pin down specifically around connectivity issues so being able to enqueue events for when the network connection isn’t in trouble would be greatly advantageous! :)

**Comment by jmshal** [comment]
> @eanakashima is this likely to land anytime soon?
> 
> We’ve got some issues we’re trying to pin down specifically around connectivity issues so being able to enqueue events for when the network connection isn’t in trouble would be greatly advantageous! :)

@eanakashima If the answer is *likely not*, I am happy to do some "streamlining" to reduce the bundle size this weekend.

@ticky As an aside, you can always manually patch/pull in a custom version of Bugsnag with these changes - if that's something you're into?

**Comment by btecu** [comment]
@ticky [AirBrake ](https://airbrake.io/) supports offline errors.

**Comment by eanakashima** [comment]
@ticky it's definitely on our radar, but unfortunately I don't think it's likely to land in the next week or two. As @jmshal mentioned, as an alternative, it's safe to replace the cdn-ified version of bugsnag-js with a custom version that you bundle with your own JS files (just be sure to include it first so it can shim the right things and report the greatest number of errors), so you could test a fork like this out in the meantime if you wanted to.

@jmshal if you have the time/interest, that would be most welcome. ✨

**Comment by ticky** [comment]
We’re already packaging it in with Webpack and pulling in from npm, so swapping it out for a git ref is doable!

That said, the changes in this PR seem outdated compared to the latest release, and I don’t think I have enough context to resolve the conflicts myself in a rebase!

**Comment by jmshal** [comment]
> That said, the changes in this PR seem outdated compared to the latest release, and I don’t think I have enough context to resolve the conflicts myself in a rebase!

Ah yes, sorry about that, @ticky, just sorting that out for you now.

**Comment by jmshal** [comment]
@ticky It's worth noting that this feature only works when setting `notifyHandler` to `xhr`, because the way the endpoint currently responds to the browser causes the default `notifyHandler` (using `Image` objects) to trigger the `onerror` event, as the response is not a valid renderable image.

It's also been a while since this branch was created, so I still need to fully re-test the functionality to ensure nothing has broken in the mean time. My initial post-merge tests seemed to function correctly.

**Comment by bengourley** [comment]
Need to decide whether to work this into the current version or the next major.

**Comment by bengourley** [comment]
@jmshal we're going to close this off and ensure that we add offline support to the next major version

**Comment by jmshal** [comment]
🕺 looking forward to it!

**Comment by jacobg** [comment]
@bengourley Was offline support ever added? It's particularly important for hybrid mobile apps (e.g., cordova).

**Comment by ticky** [comment]
@jacobg as far as I can tell, offline support hasn’t been added at all. #117 is still open, and I can find no indication that the library handles failures to send reports at all.

**Pull request closed without merging**
