### PR TITLE
fix: Xcode 12 compatibility

### PR DESCRIPTION
**Pull request by nvojnovic**
## Goal

Latest Xcode 12 fails to build while without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. For more details please check: [facebook/react-native#29633 (comment)](https://github.com/facebook/react-native/issues/29633#issuecomment-694187116)

## Testing

Use this branch to install with an app running on Xcode 12.

### CODE REVIEW

**Comment by xander-jones** [comment]
👋. Hey @nvojnovic, thanks for raising this with us, looks good, we're going to run this through CI and look into getting the changes merged in 😄

**Comment by DawidVanderhoven-TomTom** [comment]
Will this ever be merged?

**Comment by mattdyoung** [comment]
Hi @DawidVanderhoven-TomTom 

This was delayed whilst we were agreeing on a CI approach. It should now be merged soon. Thanks!

**Comment by mattdyoung** [comment]
This is now released in [v7.9.6](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.9.6). Thanks for the contribution!

**Pull request merged**
