### PR TITLE
Add a `Bugsnag.maxDepth` option (number) [Fixes #113]

### LINKED ISSUE #113: Bugsnag.maxDepth (=[RECURSIVE])
Hi,

I'd like to be able to set a variable ```maxDepth``` in the config.

I'am talking about this pice of code :
```javascript
if (depth >= 5) {
    return encodeURIComponent(prefix) + "=[RECURSIVE]";
}
```

Now we have the value ```5``` hardcoded. It's a little be short for me. I'd like 7.

Can we imagine use the syntax below ?

```javascript
Bugsnag.maxDepth = 7;
```

If yes, I can make the change and pull request.

### PR DESCRIPTION
**Pull request by jacobmarshall**
Originally requested by @Yappli in issue #113 (https://github.com/bugsnag/bugsnag-js/issues/113).

I also require this feature, so I thought I'd hurry this along by submitting my own PR (not that it's much of a rush, but yeah... #swag).

screenshot 2015-07-21 19 38 59

### CODE REVIEW

**Comment by snmaynard** [comment]
Perfect! Thanks @jacobmarshall!

**Comment by jessicard** [comment]
Thanks @jacobmarshall!! :heart:

**Comment by dfournier** [comment]
:+1: any idea when will it be live on CDN?

**Comment by jacobmarshall** [comment]
I thought it was already... Whoa, I never noticed! :smile:

**Pull request merged**
