### PR TITLE
CI Lerna improvements

### PR DESCRIPTION
**Pull request by Cawllec**
Attempts to combat ongoing Lerna bootstrapping failures by:
- Updating Lerna to the latest version (this seems to have little effect, but will enable new/faster lerna features)
- Setting a concurrency limit of 2 on the bootstrapping process

So far there have been no bootstrapping failures under from this setup, although the number of tests run have been very low.

In addition it was determined that adding more logging verbosity does not help with the debugging process, as the failing part of the bootstrapping is logged in full regardless.

### CODE REVIEW

**Comment by Cawllec** [comment]
The bootstrapping takes approximately 1minute 30seconds.  I don't believe this is a significant increase from the previous runs, or that it will overall effect the time taken.

**Comment by Cawllec** [comment]
Ah, it broke again unfortunately.

**Comment by Cawllec** [comment]
With concurrency set to 1 the last build took approx 4minutes, which seems like a significant slowdown.

**Comment by bengourley** [comment]
When logging was set to verbose, did lerna say anything interesting before it failed?

**Comment by Cawllec** [comment]
Nope, just listed the previous packages.  The actually error messages were identical.

**Pull request merged**
