### PR TITLE
feat(expo): Add support for Expo SDK v42

### LINKED ISSUE #1483: Expo SDK 42 support
### Describe the bug

`@bugsnag/expo` depends on `expo-constants@9.3.5` and `expo-file-system@9.3.0`, but SDK 42 ships with `expo-constants@11.0.1` and `expo-file-system@11.1.3`.

### Steps to reproduce
1. Create new expo project `expo init`
2. Install bugsnag `npm add @bugsnag/expo`
3. Build your project with EAS `eas build --platform android`

> [...]
> Make sure following dependencies of your project are resolving to one specific version:
>  expo-constants, expo-file-system
> [stderr] FAILURE: Build failed with an exception.
> [stderr] * Where:
> [stderr] Script '/build/workingdir/build/node_modules/@unimodules/core/unimodules-core.gradle' line: 15
> [stderr] * What went wrong:
> [stderr] A problem occurred evaluating project ':expo-device'.
> [stderr] > Project with path ':unimodules-permissions-interface' could not be found in project ':expo-device'.
> [...]

### Environment

* Bugsnag version: `7.10.5`

### Example code snippet 

```
# The error occurs at build time so no code necessary, see "Steps to reproduce"
```

### PR DESCRIPTION
**Pull request by LinusU**
## Goal

In accordance with the [contribution guide](https://github.com/bugsnag/bugsnag-js/blob/next/packages/expo/CONTRIBUTING.md) and since it's needed to work correctly on the latest Expo SDK version, the version of the dependant expo libraries should match what Expo ships with.

## Design

The approach I took was to run the following commands:

```sh
npx lerna add expo-constants@~11.0.0 packages/expo packages/plugin-expo-*
npx lerna add expo-device@~3.3.0 packages/plugin-expo-device
npx lerna add expo-file-system@~11.1.0 packages/delivery-expo
```

The version was fetched from this file upstream in Expo:

https://github.com/expo/expo/blob/master/packages/expo/bundledNativeModules.json

## Changeset

The version of certain `expo-*` dependencies was changed.

## Testing

I tested this out in an Expo app by modifying my package-lock.json manually to use these versions.

-----

Fixes #1483

### CODE REVIEW

**Comment by yousif-bugsnag** [comment]
Hi @LinusU, thanks for the PR - as mentioned on #1483 we have a task to look at this in our next sprint so will make these changes as part of that work. I'm going to close out this PR but we'll let you know once this has been released via #1483

**Comment by LinusU** [comment]
Hey @yousif-bugsnag, are you not accepting outside contributions at all or is there a specific reason why this PR cannot be merged? I spent quite some time on (mostly getting the monorepo setup 😅) and it would have been nice to know upfront that you would just close it...

**Comment by yousif-bugsnag** [comment]
Hi @LinusU, my apologies for closing this PR prematurely. We're really grateful for the contribution! 

It may need some changes but we can certainly use this as a starting point, so I'm reopening this and we'll review fully as soon as we're able to.

**Review by imjoehaines — APPROVED** [review]
Thanks for the PR @LinusU!

**Comment by LinusU** [comment]
Thanks for the merge!

**Pull request merged**
