### PR TITLE
slint code, fix get component name when use script setup way

### PR DESCRIPTION
**Pull request by sald19**
## Goal

Get component name in vue3 when use script setup

CleanShot 2022-06-27 at 15 41 38@2x

### CODE REVIEW

**Comment by luke-belton** [comment]
Hi @sald19 - thanks for raising this. Please could you tell us a bit more about the problem you're trying to solve here - perhaps you could share a cut-down reproduction example? I'm still seeing the `vue.component` field set correctly in Bugsnag when using the new script syntax, i.e. `<script setup>`.

**Comment by sald19** [comment]
the `vm`  instance (ViewModel) does not have the  property `name`
CleanShot 2022-06-29 at 13 12 49

only get `__name` or `__file`

**Comment by luke-belton** [comment]
Hi @sald19 if I import a `HelloWorld` component which contains a simple call to `Bugsnag.notify(new Error('Test'))` like this:
```
<script setup>
   import HelloWorld from "./components/HelloWorld.vue";
</script>
```
I see the `vm.$options.name` property set to `HelloWorld`:

Screenshot 2022-07-05 at 15 43 00

What version of Vue are you using? Are you able to share a reproduction example to demonstrate the behaviour you're seeing?

**Comment by sald19** [comment]
my current setup is 

composer.json
```
 "inertiajs/inertia-laravel": "^0.6.3",
 "laravel/framework": "^9.19",
```

package.json
```
"@bugsnag/js": "^7.17.0",
"@bugsnag/plugin-vue": "^7.17.0",
```

**Comment by johnkiely1** [comment]
Hi @sald19, I think it would be beneficial if you could share a cut down reproduction example demonstrating the issue you are seeing, as we have been unable to reproduce it. This is likely the best way for us to progress on this. Thanks.

**Comment by luke-belton** [comment]
Hi @sald19 - it's been a little while since we heard from you on this, so I'm going to close this for now. Feel free to reopen in the future if you're able to create a reproduction example 👍

**Pull request closed without merging**
