### PR TITLE
Export BrowserBugsnagStatic

### PR DESCRIPTION
**Pull request by mdentremont**
## Goal
- Allows the correct type to be imported in projects which use bugsnag

### CODE REVIEW

**Comment by mdentremont** [comment]
Our project had some code like this and we wanted to change `trackInlineScript`, but the "browser" exported bugsnag variable doesn't export its type:
```
    const bugsnagClientPromise = new Promise<BugsnagStatic>(
      (resolve) => {
        const bugsnag = require('@bugsnag/js');
        return resolve(bugsnag);
      },
    );
```

**Comment by johnkiely1** [comment]
Hi @mdentremont, Thanks for the PR, we will look to review as soon as priorities allows.

**Comment by mdentremont** [comment]
@johnkiely1 Any chance this'll get in soonish?

**Comment by johnkiely1** [comment]
Hi @mdentremont, we don't have a definitive ETA as of yet but we are hoping to get to this soon.

**Comment by mdentremont** [comment]
@johnkiely1 Any chance you'd like to sneak this in now?

**Comment by djskinner** [comment]
Superseded by https://github.com/bugsnag/bugsnag-js/pull/2112 (so we can run this through CI and get it merged)

**Pull request closed without merging**
